import React, { useEffect, useState } from 'react'
import { ArrowUpRight, BriefcaseBusiness, Github, Instagram, Linkedin, Mail, MapPin, Menu, Mic2, Moon, Twitter, Volume2, VolumeX, X } from 'lucide-react'
import { motion } from 'framer-motion'
import CommandPalette from './CommandPalette'
import CursorField from './CursorField'
import InteractiveNodeCanvas from './InteractiveNodeCanvas'
import ProofShowcase from './ProofShowcase'
import RoiCalculator from './RoiCalculator'

const links = [['home', 'Home'], ['story', 'Story'], ['about', 'About'], ['skills', 'Skills'], ['projects', 'Projects'], ['learning', 'Learning'], ['business', 'Business'], ['contact', 'Contact']] as const
const socials = [{ label: 'GitHub', href: 'https://github.com/jaikishore2026-max', icon: Github }, { label: 'Instagram', href: 'https://www.instagram.com/jaikishorel0_?stkn=MWV4ZHB6ajR2eTJpdw==', icon: Instagram }, { label: 'LinkedIn', href: 'https://linkedin.com', icon: Linkedin }, { label: 'Twitter', href: 'https://twitter.com', icon: Twitter }]
const storyPhases = [{ number: '01', title: 'Origin', year: '2023 — 2024', tag: 'THE SPARK', body: 'Curiosity in tech, self-learning, and business became a daily practice. Small tools and experiments made the power of creating feel real.' }, { number: '02', title: 'Skill Building', year: '2024 — 2025', tag: 'THE GRIND', body: 'Web development, AI tools, and consistent daily learning turned curiosity into technical foundations and real-world product instincts.' }, { number: '03', title: 'Breakthrough', year: '2025', tag: 'THE MOMENT', body: 'Public speaking in front of 500+ people proved that clear communication is a force multiplier for every idea.', link: 'https://www.youtube.com/live/rYltVZPwlsA?si=PRk4DTXNq7Akj5sk&t=18464' }, { number: '04', title: 'Execution', year: '2026 — Present', tag: 'THE BUILD', body: 'Building personal brand, shipping projects, and adopting a startup mindset — moving from learning to creating and scaling.' }]
const skillSpecs = [{ name: 'Python', type: 'PROGRAMMING', level: '75%', proof: 'AI tooling / automation' }, { name: 'C++', type: 'PROGRAMMING', level: '69%', proof: 'systems thinking' }, { name: 'Java', type: 'PROGRAMMING', level: '52%', proof: 'core foundations' }, { name: 'Social Media Growth', type: 'GROWTH', level: '81%', proof: 'community systems' }, { name: 'Brand & Copywriting', type: 'GROWTH', level: '60%', proof: 'message architecture' }, { name: 'Community Orchestration', type: 'GROWTH', level: '90%', proof: 'people / momentum' }, { name: 'Outreach & Ads Strategy', type: 'GROWTH', level: '80%', proof: 'distribution loops' }]
const businessCards = [{ title: 'Startup Mindset', body: 'Seeing problems, building solutions, moving fast, and iterating based on market feedback.', focus: 'Problem-solving approach' }, { title: 'Product Thinking', body: 'Understanding user problems deeply, designing solutions that matter, measuring impact, and continuously improving.', focus: 'User-centric development' }, { title: 'Business Fundamentals', body: 'Revenue models, unit economics, customer acquisition, retention, and how tech businesses actually work.', focus: 'Growth & sustainability' }, { title: 'Leadership Development', body: 'Communicating vision, building teams, making decisions under uncertainty, and inspiring others to execute.', focus: 'Team execution' }]

function Reveal({ children, delay = 0, className = '' }: { children: React.ReactNode; delay?: number; className?: string }) { return <motion.div className={className} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .16 }} transition={{ duration: .65, delay, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div> }
function SectionHeading({ index, label, title, body }: { index: string; label: string; title: React.ReactNode; body: string }) { return <div className="new-section-heading"><div className="tech-label"><span className="pulse-dot" /> {index} / {label}</div><h2>{title}</h2><p>{body}</p></div> }

export default function FuturePortfolio() {
  const [menuOpen, setMenuOpen] = useState(false); const [theme, setTheme] = useState<'obsidian' | 'aurora'>('obsidian'); const [sound, setSound] = useState(false)
  const playTick = () => { if (!sound) return; const context = new AudioContext(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.frequency.value = 520; gain.gain.value = .025; oscillator.connect(gain); gain.connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + .045) }
  useEffect(() => { document.documentElement.dataset.theme = theme; return () => { delete document.documentElement.dataset.theme } }, [theme])
  const toggleTheme = () => setTheme(theme === 'obsidian' ? 'aurora' : 'obsidian')

  return <div className={`site-shell premium-shell handcrafted-shell ${theme === 'aurora' ? 'theme-aurora' : ''}`} onClick={playTick}>
    <CursorField /><div className="blueprint-grid" aria-hidden="true" /><CommandPalette theme={theme} onThemeToggle={toggleTheme} />
    <header className="site-nav premium-nav"><a className="brand-mark" href="#home"><span>JK</span><b>JAIKISHORE <i>/ 01</i></b></a><nav className="desktop-nav" aria-label="Primary navigation">{links.map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav><div className="nav-actions"><button className="sound-toggle" onClick={() => setSound(!sound)} aria-label={sound ? 'Turn sound off' : 'Turn sound on'}>{sound ? <Volume2 size={15} /> : <VolumeX size={15} />}</button><div className="nav-socials"><a href={socials[0].href} target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={16} /></a><a href={socials[1].href} target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={16} /></a></div><a href="#contact" className="nav-cta">Connect <ArrowUpRight size={15} /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></div></header>
    {menuOpen && <div className="mobile-menu">{links.map(([id, label]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}<ArrowUpRight size={14} /></a>)}</div>}

    <main>
      <section id="home" className="page-section premium-hero"><div className="hero-copy"><Reveal><div className="status-badge"><span className="status-dot" /> AMBITION IN PROGRESS</div></Reveal><Reveal delay={.08}><h1 className="display-heading hero-title">Building the <span>future</span><br />with code <i>&amp;</i> vision.</h1></Reveal><Reveal delay={.14}><p className="hero-subtitle">Jaikishore is a 17-year-old tech builder and CMO at Falkon Labs, turning technical curiosity into products, communities, and momentum.</p></Reveal><Reveal delay={.18}><p className="editorial-quote">&ldquo;The best way to predict the future is to build it.&rdquo;</p></Reveal><Reveal delay={.2} className="hero-actions"><a href="#projects" className="button button-primary">Enter the work <ArrowUpRight size={16} /></a><a href="#contact" className="button button-ghost">Start a conversation <Mail size={16} /></a></Reveal><Reveal delay={.28} className="hero-readout"><span><b>500+</b> room-scale speaker</span><span><b>+150%</b> community growth</span><span><b>03</b> years building</span></Reveal></div><Reveal delay={.16} className="hero-dashboard"><div className="dashboard-chrome"><span><i /><i /><i /></span><small>jk://command-center</small><em>LIVE <b /></em></div><div className="dashboard-content"><div className="dashboard-kicker">OPERATING PROFILE / 2026</div><strong>IDEA → SIGNAL<br /><span>→ SYSTEM → PROOF</span></strong><div className="dashboard-metrics"><div><small>ACTIVE MODE</small><b>BUILDING</b></div><div><small>BASE</small><b>INDIA / INTERNET</b></div></div><div className="dashboard-scan"><span /><span /><span /><span /><span /><span /><span /><span /></div><div className="dashboard-status"><span><i className="pulse-dot" /> all systems curious</span><small>explore the logbook <ArrowUpRight size={13} /></small></div></div></Reveal><a href="#story" className="scroll-cue"><span /> SCROLL TO EXPLORE</a></section>

      <section id="story" className="page-section premium-section"><Reveal><SectionHeading index="01" label="FOUNDER STORY / LOGBOOK" title={<>Four phases. One <span>direction.</span></>} body="The moments that shaped how I think, build, and communicate — from curiosity to execution." /></Reveal><div className="story-logbook">{storyPhases.map((phase, index) => <Reveal key={phase.number} delay={index * .07} className="story-log-entry"><div className="story-log-index">{phase.number}</div><div className="story-log-main"><div><span className="story-log-tag">{phase.tag}</span><time>{phase.year}</time></div><h3>{phase.title}</h3><p>{phase.body}</p>{phase.link && <a href={phase.link} target="_blank" rel="noreferrer">Watch the keynote <ArrowUpRight size={14} /></a>}</div><span className="story-log-mark">✳</span></Reveal>)}</div><div className="story-stat-strip"><span><b>04</b> phases</span><span><b>500+</b> audience</span><span><b>03y</b> journey</span></div></section>

      <section id="about" className="page-section premium-section about-editorial"><Reveal><SectionHeading index="02" label="PROFILE" title={<>A builder with a <span>growth loop.</span></>} body="I sit at the intersection of engineering foundations and digital growth. That means I care about the architecture, the story, and the people who use it." /></Reveal><div className="about-editorial-grid"><Reveal><div className="editorial-note"><span>NOTE / 001</span><strong>Make the next<br /><em>version real.</em></strong><p>The goal isn&apos;t to look busy. It&apos;s to keep learning, keep shipping, and make the signal clearer.</p></div></Reveal><Reveal delay={.1}><div className="identity-card"><span>JAIKISHORE G.V.</span><strong>Tech Builder<br />Marketing Lead</strong><small>High School Graduate · CS &amp; Business Self-Learning</small><div className="identity-line" /></div></Reveal></div></section>

      <section id="network" className="page-section premium-section"><Reveal><SectionHeading index="03" label="INTERACTIVE NETWORK" title={<>The way I think is a <span>connected system.</span></>} body="Drag the nodes. Zoom into the relationships. Strategy, execution, and growth only become valuable when they talk to each other." /></Reveal><Reveal delay={.1}><InteractiveNodeCanvas /></Reveal></section>

      <section id="skills" className="page-section premium-section"><Reveal><SectionHeading index="04" label="SKILLS / SPEC SHEET" title={<>Capability is a <span>practice.</span></>} body="Keep the numbers honest, but let the work explain what they mean. Technical foundations and growth instincts, side by side." /></Reveal><div className="skill-spec-grid">{skillSpecs.map((skill, index) => <Reveal key={skill.name} delay={index * .035}><div className="skill-spec"><span className="skill-spec-type">{skill.type}</span><strong>{skill.name}</strong><small>{skill.proof}</small><em>{skill.level}</em></div></Reveal>)}</div><div className="skill-spec-footer"><span>PYTHON / C++ / JAVA / WEB DEV / AI ENGINEERING</span><a href="#proof">Inspect code proof <ArrowUpRight size={14} /></a></div></section>

      <section id="proof" className="page-section premium-section"><Reveal><SectionHeading index="05" label="PROOF OVER PERCENTAGES" title={<>Don&apos;t take my word for it.<br /><span>Inspect the work.</span></>} body="Syntax, systems, and micro-case studies — the proof behind the spec sheet." /></Reveal><Reveal delay={.1}><ProofShowcase /></Reveal></section>

      <section id="projects" className="page-section premium-section"><Reveal><SectionHeading index="06" label="SELECTED PROJECTS" title={<>Projects with a <span>feedback loop.</span></>} body="Technical products, growth campaigns, and room-scale communication built to make the next decision clearer." /></Reveal><div className="premium-project-grid"><Reveal className="premium-project-card project-land"><div className="project-index">PROJECT 01 <span>TECH / SYSTEMS</span></div><div className="project-radar"><div /><span>LANDSORA / LIVE</span></div><div className="premium-project-copy"><div><h3>Landsora</h3><p>IoT landslide early-warning console with deterministic validation, simulated telemetry, and explainable AI for emergency teams.</p><div className="project-tags"><span>React / TypeScript</span><span>IoT / AI</span><span>Risk systems</span></div></div><a href="https://github.com/jaikishore2026-max/landSora" target="_blank" rel="noreferrer" aria-label="Open Landsora"><Github size={19} /></a></div></Reveal><Reveal className="premium-project-card project-falkon" delay={.1}><div className="project-index">PROJECT 02 <span>GROWTH / COMMUNITY</span></div><h3>Falkon Labs Growth Campaign</h3><p>Social strategy, content hooks, visual brand assets, and community systems that created measurable momentum.</p><div className="falkon-number">+150<span>%</span></div><RoiCalculator /></Reveal></div><Reveal delay={.16}><div className="speaking-project"><div><span className="project-index">PROJECT 03 / LEADERSHIP</span><h3>Public Speaking <em>In Front Of A Massive Crowd</em></h3><p>Took the stage in front of 500+ attendees and cultivated high-level relationships by orchestrating the formal invitation and protocol for distinguished chief guests.</p></div><a href="https://www.youtube.com/live/rYltVZPwlsA?si=PRk4DTXNq7Akj5sk&t=18464" target="_blank" rel="noreferrer"><Mic2 size={17} /> Watch keynote <ArrowUpRight size={15} /></a></div></Reveal></section>

      <section id="learning" className="page-section premium-section learning-section"><Reveal><SectionHeading index="07" label="CURRENTLY LEARNING" title={<>Always in <span>beta.</span></>} body="The current learning queue: concepts I am actively turning into capability." /></Reveal><div className="learning-command-grid"><Reveal><div className="learning-cell"><span>01 / AI ENGINEERING</span><strong>Models that<br /><em>do useful work.</em></strong><p>LLMs, prompt systems, and intelligent product features.</p></div></Reveal><Reveal delay={.08}><div className="learning-cell violet-cell"><span>02 / SYSTEM DESIGN</span><strong>Architecture<br /><em>with a reason.</em></strong><p>Data flow, scalability patterns, and production thinking.</p></div></Reveal><Reveal delay={.16}><div className="learning-cell emerald-cell"><span>03 / STARTUP BUILDING</span><strong>Ship the<br /><em>next version.</em></strong><p>Founder mindset, product-market fit, and iteration.</p></div></Reveal><Reveal delay={.24}><div className="learning-cell amber-cell"><span>04 / TRADING &amp; MARKETS</span><strong>Read the<br /><em>moving signal.</em></strong><p>Learning market structure, risk management, technical analysis, and disciplined decision-making.</p></div></Reveal><Reveal delay={.32}><div className="learning-cell java-cell"><span>05 / JAVA FOUNDATIONS</span><strong>Strong core<br /><em>before scale.</em></strong><p>Building object-oriented fluency through practical console projects and game experiments.</p></div></Reveal></div></section>

      <section id="business" className="page-section premium-section"><Reveal><SectionHeading index="08" label="BUSINESS THINKING" title={<>Think in <span>systems.</span></>} body="Technology makes the solution possible. Product thinking makes it matter." /></Reveal><div className="business-grid">{businessCards.map((card, index) => <Reveal key={card.title} delay={index * .06}><div className="business-card"><span>0{index + 1}</span><h3>{card.title}</h3><p>{card.body}</p><small>{card.focus}</small></div></Reveal>)}</div></section>

      <section id="contact" className="page-section premium-section contact-section"><Reveal><div className="contact-panel premium-contact"><div className="contact-copy"><div className="tech-label"><span className="pulse-dot" /> OPEN CHANNEL</div><h2 className="display-heading">Have a bold idea?<br /><span>Let&apos;s make it real.</span></h2><p>Interested in scaling a community or discussing software projects? Let&apos;s build something exceptional.</p><a className="email-link" href="mailto:mailme.jaikishore2026@gmail.com">mailme.jaikishore2026@gmail.com <ArrowUpRight size={16} /></a><div className="contact-details"><span><MapPin size={14} /> India</span><span><BriefcaseBusiness size={14} /> CMO at Falkon Labs</span></div></div><div className="contact-actions"><a className="button button-primary" href="mailto:mailme.jaikishore2026@gmail.com">Start a conversation <Mail size={16} /></a><span>or press <kbd>⌘ K</kbd> to navigate the system</span><div className="theme-note"><Moon size={14} /> theme: {theme} <button onClick={toggleTheme}>switch</button></div></div></div></Reveal></section>
    </main>

    <footer className="site-footer premium-footer"><div><a className="brand-mark" href="#home"><span>JK</span><b>JAIKISHORE <i>/ 01</i></b></a><p>Building the future with code &amp; vision.</p></div><div className="footer-links">{socials.map(({ label, href, icon: Icon }) => <a key={label} href={href} target="_blank" rel="noreferrer"><Icon size={15} /> {label}</a>)}<a href="mailto:mailme.jaikishore2026@gmail.com"><Mail size={15} /> Email</a></div><small>© {new Date().getFullYear()} JAIKISHORE / ALL SYSTEMS BUILDING</small></footer>
  </div>
}
