import React, { useState } from 'react'
import { Code2, Copy, Mic2, TrendingUp } from 'lucide-react'

const proofs = [
  { id: 'python', label: 'Python / AI', icon: Code2, title: 'Build systems that explain themselves.', metric: 'automation + intelligence', code: <><span className="code-key">def</span> <span className="code-fn">explain_signal</span>(signal):<br />&nbsp;&nbsp;<span className="code-key">return</span> {`{`}<br />&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-string">&quot;signal&quot;</span>: signal,<br />&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-string">&quot;confidence&quot;</span>: <span className="code-number">0.94</span>,<br />&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-string">&quot;next_action&quot;</span>: <span className="code-string">&quot;measure again&quot;</span><br />&nbsp;&nbsp;{`}`}</>, detail: 'From sensor telemetry to explainable risk layers in Landsora.' },
  { id: 'cpp', label: 'C++ / Core', icon: Code2, title: 'Learn close to the machine.', metric: 'systems thinking', code: <><span className="code-type">vector</span>&lt;<span className="code-type">int</span>&gt; signals {`{`}<span className="code-number">12</span>, <span className="code-number">18</span>, <span className="code-number">27</span>{`}`};<br /><span className="code-key">for</span> (<span className="code-type">auto</span> value : signals) {`{`}<br />&nbsp;&nbsp;<span className="code-key">if</span> (value &gt; threshold) trigger();<br />{`}`}</>, detail: 'Small experiments become better product instincts when the fundamentals are visible.' },
  { id: 'growth', label: 'Falkon Labs', icon: TrendingUp, title: 'Distribution is designed.', metric: '+150% community reach', code: <><span className="code-key">const</span> loop = [<span className="code-string">&apos;listen&apos;</span>, <span className="code-string">&apos;ship&apos;</span>, <span className="code-string">&apos;measure&apos;</span>, <span className="code-string">&apos;repeat&apos;</span>];<br /><span className="code-fn">loop</span>.forEach(step =&gt; growth.<span className="code-fn">compound</span>(step));</>, detail: 'A social strategy system that translated consistency into measurable community momentum.' },
  { id: 'speaking', label: 'Public Speaking', icon: Mic2, title: 'Clarity scales across a room.', metric: '500+ people reached', code: <><span className="code-key">const</span> room = <span className="code-number">500</span>;<br /><span className="code-key">const</span> message = <span className="code-string">&apos;make the idea memorable&apos;</span>;<br /><span className="code-fn">communicate</span>(message, room);</>, detail: 'A keynote became proof that communication is a technical advantage, not a soft extra.' },
]

export default function ProofShowcase() {
  const [active, setActive] = useState('python')
  const [copied, setCopied] = useState(false)
  const proof = proofs.find((item) => item.id === active) || proofs[0]
  const Icon = proof.icon
  return <div className="proof-showcase"><div className="proof-tabs">{proofs.map((item) => { const TabIcon = item.icon; return <button key={item.id} className={active === item.id ? 'is-active' : ''} onClick={() => setActive(item.id)}><TabIcon size={15} /> {item.label}</button> })}</div><div className="proof-grid"><div className="proof-copy"><div className="proof-icon"><Icon size={21} /></div><span className="tech-label">{proof.metric}</span><h3>{proof.title}</h3><p>{proof.detail}</p><div className="proof-stamp"><span className="pulse-dot" /> PROOF LOG / VERIFIED BY SHIPPING</div></div><div className="code-window"><div className="code-top"><span><i /><i /><i /></span><button onClick={() => { setCopied(true); setTimeout(() => setCopied(false), 1200) }}><Copy size={13} /> {copied ? 'COPIED' : 'COPY'}</button></div><pre><code>{proof.code}</code></pre></div></div></div>
}
